extends SceneTree
## Curves, event gates, instance isolation, modifiers and bounded save/wire values.

var failures: int = 0

func check(ok: bool, message: String) -> void:
	if not ok:
		failures += 1
		printerr("FAIL: ", message)

func _initialize() -> void:
	var progress := CharacterProgress.new()
	var other := CharacterProgress.new()
	check(progress.level() == 1 and progress.skill("sword") == 1, "new characters start at one")
	check(progress.damage_multiplier("sword") == 1 and progress.walk_multiplier() == 1, "baseline gameplay preserved")
	for hit in 19: progress.weapon_hit("sword")
	check(progress.skill("sword") == 1, "rank requires its full practice cost")
	progress.weapon_hit("sword")
	check(progress.skill("sword") == 2 and progress.skill("fist") == 1, "twentieth hit ranks only the trained weapon")
	check(other.practice.sword == 0, "practice belongs to one character")
	progress.weapon_hit("magic")
	progress.weapon_hit("attack_speed")
	progress.award_experience(100)
	check(progress.level() == 2 and progress.experience == 100, "four slime kills reach character level two")
	check(progress.practice.magic == 0 and progress.practice.attack_speed == 0, "kills and weapon hits never train magic or speed")
	progress.mana_spent(19)
	progress.mana_spent(0)
	progress.mana_spent(-50)
	check(progress.practice.magic == 19 and progress.skill("magic") == 1, "only positive mana spent trains magic")
	progress.mana_spent(1)
	check(progress.skill("magic") == 2, "mana cost crosses magic threshold")
	for block in 20: progress.defended()
	check(progress.skill("defence") == 2 and progress.incoming_multiplier() < 1, "guards train useful defence")
	check(progress.damage_multiplier("sword") > progress.damage_multiplier("fist"), "weapon skill adds damage beyond character level")
	check(progress.walk_multiplier() > 1 and progress.attack_multiplier() > 1, "character level improves movement and attack rate")
	for level in range(2, 99):
		check(CharacterProgress.requirement(level) > CharacterProgress.requirement(level - 1), "skill curve grows at every rank")
		check(CharacterProgress.rank(CharacterProgress.threshold(level)) == level, "exact cumulative threshold ranks correctly")
		check(CharacterProgress.rank(CharacterProgress.threshold(level) - 1) == level - 1, "one point short never ranks early")
	progress.award_experience(100000000)
	progress.mana_spent(100000000)
	progress.speed_gear_trained(100000000)
	check(progress.level() == 99 and progress.skill("magic") == 99 and progress.skill("attack_speed") == 99, "large awards stop at 99")
	check(progress.walk_multiplier() <= 1.20 and progress.attack_multiplier() <= 1.50, "speed bonuses remain bounded")
	check(progress.incoming_multiplier() > 0.65 and progress.damage_multiplier("sword") < 3.5, "high ranks retain combat risk")
	for hit in 79: progress.weapon_hit("shooting")
	check(progress.skill("shooting") == 1, "shooting needs four times as many hits as melee")
	progress.weapon_hit("shooting")
	check(progress.skill("shooting") == 2 and progress.display().skills.shooting.percent == 0, "eightieth hit ranks shooting with exact HUD progress")
	check(progress.shooting_spread_multiplier() < 1.0, "shooting rank improves accuracy")
	check(progress.damage_multiplier("shooting") > progress.damage_multiplier("fist"), "shooting rank improves damage")
	var legacy := other.capture()
	legacy.practice.erase("shooting")
	check(SaveStore.progression(legacy) and ExplorationProtocol.progression(legacy), "old five-skill saves remain valid")
	other.restore(legacy)
	check(other.skill("shooting") == 1, "old saves begin shooting at rank one")
	check(is_equal_approx(CombatTuning.new().punch_cooldown, CombatTuning.new().swing_seconds), "basic fist cadence matches sword swing")
	var saved := progress.capture()
	other.restore(JSON.parse_string(JSON.stringify(saved)))
	check(other.stat_points == progress.stat_points and other._granted_level == progress._granted_level, "stat points survive JSON round trip")
	check(other.capture().version == 2, "captured progression uses version 2")
	check(SaveStore.progression(saved) and ExplorationProtocol.progression(saved), "save and wire accept complete progression")
	for invalid: Variant in [-1, 1.5, INF, NAN, "20", 100000001]:
		var bad := saved.duplicate(true)
		bad.practice.sword = invalid
		check(not SaveStore.progression(bad) and not ExplorationProtocol.progression(bad), "both boundaries reject malformed counters")
	var missing := saved.duplicate(true)
	missing.practice.erase("magic")
	check(not SaveStore.progression(missing) and not ExplorationProtocol.progression(missing), "partial records cannot silently lose skills")
	other.restore({}, 100)
	check(other.level() == 2 and other.skill("magic") == 1, "legacy EXP migrates with fresh practice")
	# Stat point allocation tests
	var sp := CharacterProgress.new()
	check(sp.stat_points == 0, "fresh character has no stat points")
	sp.award_experience(100)
	check(sp.level() == 2 and sp.stat_points == 1, "level 2 grants one stat point")
	var base_sword := sp.skill("sword")
	check(sp.allocate_stat("sword"), "valid allocation succeeds")
	check(sp.stat_points == 0, "stat point is consumed on allocation")
	check(sp.skill("sword") == base_sword + 1, "allocated stat point raises skill rank by one")
	check(not sp.allocate_stat("fist"), "allocation fails with zero remaining points")
	sp.award_experience(100000000)
	check(sp.level() == 99, "max level is 99")
	check(sp.stat_points == 97, "levels 3-99 grant 97 more points")
	while sp.stat_points > 0: sp.allocate_stat("sword")
	check(sp.skill("sword") == 99, "allocating raises sword to cap")
	sp.stat_points = 1
	check(not sp.allocate_stat("sword"), "cannot allocate past cap even with a point available")
	var sp_saved := sp.capture()
	var sp2 := CharacterProgress.new()
	sp2.restore(JSON.parse_string(JSON.stringify(sp_saved)))
	check(sp2.stat_points == sp.stat_points and sp2._granted_level == sp._granted_level, "stat points and granted level survive round trip")
	check(sp2.skill("sword") == sp.skill("sword"), "allocated stats survive round trip")
	# QuestState tests
	var quest := QuestState.new()
	check(quest.status == QuestState.Status.NOT_STARTED, "quest starts not started")
	check(not quest.record_kill(), "cannot record kill before accepting")
	quest.start()
	check(quest.status == QuestState.Status.IN_PROGRESS, "quest starts on accept")
	for _k in 49: quest.record_kill()
	check(quest.current_count == 49 and quest.status == QuestState.Status.IN_PROGRESS, "49 kills not enough to complete")
	quest.record_kill()
	check(quest.current_count == 50 and quest.status == QuestState.Status.COMPLETED, "50th kill completes quest")
	check(quest.claim_reward(), "reward can be claimed on completion")
	check(quest.status == QuestState.Status.REWARDED, "quest moves to rewarded state")
	check(not quest.claim_reward(), "cannot claim a reward twice")
	var q_saved := quest.capture()
	var quest2 := QuestState.new()
	quest2.restore(q_saved)
	check(quest2.status == QuestState.Status.REWARDED and quest2.current_count == 50, "quest state survives save/restore")
	var motor := PlayerMotor.new(PlayerTuning.new())
	motor.walk_multiplier = 1.196
	var command := PlayerCommand.new()
	command.move = Vector2.RIGHT
	var velocity := motor.step(command, Vector3.ZERO, true, 1)
	check(is_equal_approx(velocity.x, PlayerTuning.new().walk_speed * 1.196), "walk bonus is applied after input normalization")
	var melee := MeleeRules.new(CombatTuning.new())
	melee.cooldown = 0.6
	melee.step(false, 0.2, 1.5)
	check(is_equal_approx(melee.cooldown, 0.3), "attack rate accelerates cooldown without changing charge requirements")
	print("Progression: ", "PASS" if failures == 0 else "FAIL")
	quit(1 if failures else 0)
