extends SceneTree
## Focused authority-rule boundaries; no scene or presentation wiring.

var failures: int = 0

func _initialize() -> void: call_deferred("run")

func check(value: bool, description: String) -> void:
	if value: return
	failures += 1
	push_error("FAIL: " + description)

func run() -> void:
	_test_press()
	_test_cut()
	_test_pack()
	_test_live_and_malformed()
	_test_accessible()
	print("Tofu Production Rules: ", "PASS" if failures == 0 else "FAIL")
	quit(1 if failures > 0 else 0)

func _test_press() -> void:
	var press := TofuPressRules.new()
	check(press.begin_traditional(TofuPressRules.Sample.SOFT, 1, 10.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "soft begins")
	check(press.place_stone("stone_1", 2, 10.0, press.revision) == TofuPressRules.Outcome.INVALID, "other actor cannot place")
	check(press.place_stone("stone_1", 1, 10.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "one stone starts timing")
	check(press.release_traditional(1, 13.75, press.revision) == TofuPressRules.Outcome.CERTIFIED, "soft upper time boundary")
	check(press.begin_traditional(TofuPressRules.Sample.FIRM, 1, 20.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "firm begins")
	check(press.place_stone("stone_1", 1, 20.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "first firm stone")
	check(press.place_stone("stone_2", 1, 21.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "second firm stone starts timing")
	check(press.release_traditional(1, 25.24, press.revision) == TofuPressRules.Outcome.REJECTED, "early release is one mistake")
	check(press.release_traditional(1, 26.0, press.revision) == TofuPressRules.Outcome.INVALID, "replay cannot be another mistake")
	check(press.clear_rejection(), "clearing after combat")
	check(press.begin_traditional(TofuPressRules.Sample.FIRM, 1, 30.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "firm retry")
	check(press.place_stone("stone_1", 1, 30.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "firm stone one retry")
	check(press.place_stone("stone_2", 1, 30.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "firm stone two retry")
	check(press.release_traditional(1, 34.25, press.revision) == TofuPressRules.Outcome.CERTIFIED, "firm lower boundary")
	check(press.start_modern(1, 40.0, press.revision) == TofuPressRules.Outcome.ACCEPTED, "modern starts after certificates")
	check(is_equal_approx(press.gauge(46.56), 82.0), "authority gauge calibration")
	check(press.stop_modern(1, 47.2, press.revision) == TofuPressRules.Outcome.CERTIFIED, "modern upper gauge boundary")
	check(press.certificates.all(func(value: bool) -> bool: return value), "three certificates")
	var saved := press.capture()
	var restored := TofuPressRules.new()
	check(restored.restore(saved) and restored.certificates[2], "certificates restore")
	var canceled := TofuPressRules.new()
	check(canceled.begin_traditional(TofuPressRules.Sample.SOFT, 4, 5.0, 0) == TofuPressRules.Outcome.ACCEPTED, "disconnect trial starts")
	canceled.release_lease(4)
	check(not canceled.certificates[0] and canceled.active_sample == -1, "disconnect cannot certify")
	var extra := TofuPressRules.new()
	extra.begin_traditional(TofuPressRules.Sample.SOFT, 1, 0.0, 0)
	extra.place_stone("stone_1", 1, 0.0, extra.revision)
	check(extra.place_stone("stone_2", 1, 0.1, extra.revision) == TofuPressRules.Outcome.REJECTED, "third-capacity stone rejects soft sample")
	var gauge_fail := TofuPressRules.new()
	gauge_fail.certificates = [true, true, false]
	gauge_fail.start_modern(1, 0.0, 0)
	check(gauge_fail.stop_modern(1, 6.55, gauge_fail.revision) == TofuPressRules.Outcome.REJECTED, "early gauge stop rejects")
	check(gauge_fail.stop_modern(1, 7.0, gauge_fail.revision) == TofuPressRules.Outcome.INVALID, "gauge replay cannot reject twice")

func _test_cut() -> void:
	var cut := TofuCutRules.new()
	check(cut.issue_block("batch_1_block_1", 600.0), "block issued")
	check(cut.commit("batch_1_block_1", [100.0, 200.0, 200.0, 400.0, 500.0], cut.revision) == TofuCutRules.Outcome.INVALID, "duplicate cut is malformed")
	check(cut.commit("batch_1_block_1", [100.0, 300.0, 200.0, 400.0, 500.0], cut.revision) == TofuCutRules.Outcome.INVALID, "crossed cuts malformed")
	check(cut.commit("batch_1_block_1", [100.0, 200.0, 300.0, 400.0, 601.0], cut.revision) == TofuCutRules.Outcome.INVALID, "external cut malformed")
	check(cut.commit("batch_1_block_1", [100.0, 200.0, 300.0, 400.0, 500.0], cut.revision) == TofuCutRules.Outcome.COMPLETE, "six exact widths")
	check(cut.widths.size() == 6 and is_equal_approx(cut.widths[5], 100.0), "end width evaluated")
	check(cut.commit("batch_1_block_1", [100.0, 200.0, 300.0, 400.0, 500.0], cut.revision) == TofuCutRules.Outcome.INVALID, "completion replay invalid")
	var bad := TofuCutRules.new()
	bad.issue_block("batch_1_block_2", 600.0)
	check(bad.commit("batch_1_block_2", [100.0, 200.0, 300.0, 400.0, 494.0], bad.revision) == TofuCutRules.Outcome.REJECTED, "far end piece outside five percent")
	check(bad.commit("batch_1_block_2", [100.0, 200.0, 300.0, 400.0, 494.0], bad.revision) == TofuCutRules.Outcome.INVALID, "rejected block replay invalid")
	check(bad.clear_rejection() and bad.issue_block("batch_1_block_3", 600.0), "fresh block after combat")
	check(bad.commit("batch_1_block_3", [95.0, 195.0, 295.0, 395.0, 495.0], bad.revision) == TofuCutRules.Outcome.COMPLETE, "five-percent edge accepted")
	var restored := TofuCutRules.new()
	check(restored.restore(cut.capture()) and restored.completed and restored.widths.size() == 6, "cut result restores")

func _test_pack() -> void:
	var pack := TofuPackRules.new()
	check(pack.begin_batch("batch_1"), "pack batch begins")
	check(pack.slab_id(0) != pack.slab_id(1), "slabs have distinct IDs")
	for index in 6:
		check(pack.reserve(index, 1, pack.revision) == TofuPackRules.Outcome.RESERVED, "slab reserved %d" % index)
		check(pack.reserve(index, 2, pack.revision) == TofuPackRules.Outcome.INVALID, "second actor cannot reserve %d" % index)
		check(pack.place(index, index, 1, pack.revision) == TofuPackRules.Outcome.PLACED, "slab placed %d" % index)
		var expected: int = TofuPackRules.Outcome.BOSS_READY if index == 5 else TofuPackRules.Outcome.SEALED
		check(pack.seal(index, pack.revision) == expected, "slot sealed %d" % index)
	check(pack.boss_ready and pack.seal(5, pack.revision) == TofuPackRules.Outcome.INVALID, "boss triggers once")
	var restored := TofuPackRules.new()
	check(restored.restore(pack.capture()) and restored.boss_ready, "packed state restores")
	var lease := TofuPackRules.new()
	lease.begin_batch("batch_2")
	lease.reserve(0, 7, lease.revision)
	lease.release_actor(7)
	check(lease.reserve(0, 8, lease.revision) == TofuPackRules.Outcome.RESERVED, "disconnect returns slab reservation")

func _test_live_and_malformed() -> void:
	var press := TofuPressRules.new()
	press.certificates = [true, true, false]
	press.start_modern(7, 12.0, press.revision)
	check(press.poll_modern(19.2) == TofuPressRules.Outcome.INVALID, "inclusive 90 gauge does not auto reject")
	var live := TofuPressRules.new()
	var packet: Dictionary = JSON.parse_string(JSON.stringify(press.capture(true)))
	check(live.restore(packet, true) and live.lease_actor == 7 and live.revision == press.revision, "live snapshot preserves trial and revision")
	check(is_equal_approx(live.gauge(19.0), press.gauge(19.0)), "live timing follows authority start")
	for paused_frame in 60:
		check(press.poll_modern(19.0) == TofuPressRules.Outcome.INVALID, "paused authority time does not overshoot")
	check(is_equal_approx(press.gauge(19.0), 87.5), "frozen authority time preserves pressure")
	var voluntary := TofuPressRules.new()
	voluntary.certificates = [true, true, false]
	voluntary.start_modern(7, 0.0, voluntary.revision)
	check(voluntary.abandon_active(8, voluntary.revision) == TofuPressRules.Outcome.INVALID, "other actor cannot abandon station")
	check(voluntary.abandon_active(7, voluntary.revision) == TofuPressRules.Outcome.REJECTED, "explicit abandonment rejects active trial")
	check(voluntary.abandon_active(7, voluntary.revision) == TofuPressRules.Outcome.INVALID, "abandon replay creates no second rejection")
	var reload := TofuPressRules.new()
	check(reload.restore(packet) and reload.active_sample == -1 and not reload.certificates[2], "reload cancels unfinished trial")
	check(press.poll_modern(19.201) == TofuPressRules.Outcome.REJECTED, "unattended overshoot is one rejection")
	check(press.poll_modern(20.0) == TofuPressRules.Outcome.INVALID, "overshoot poll cannot reject twice")
	var invalid: Dictionary = live.capture(true)
	invalid.revision = 0.5
	check(not reload.restore(invalid), "fractional press revision rejected")
	invalid = live.capture(true)
	invalid.active_sample = 0
	check(not reload.restore(invalid), "already-certified active sample rejected")
	var cut := TofuCutRules.new()
	cut.issue_block("block", 6.0)
	check(cut.commit("block", [1.0, 2.0, 3.0, 4.0, 4.9], cut.revision) == TofuCutRules.Outcome.REJECTED, "inaccurate plan accepted as mistake")
	check(cut.widths.size() == 6 and is_equal_approx(cut.widths[5], 1.1), "failed slice widths retained for display")
	var restored_cut := TofuCutRules.new()
	check(restored_cut.restore(JSON.parse_string(JSON.stringify(cut.capture()))) and restored_cut.rejected, "failed widths restore")
	invalid = cut.capture()
	invalid.completed = true
	invalid.rejected = false
	check(not restored_cut.restore(invalid), "inaccurate saved certificate rejected")
	cut.clear_rejection()
	check(cut.widths.is_empty(), "refill clears rejected slice geometry")
	var pack := TofuPackRules.new()
	pack.begin_batch("batch")
	pack.reserve(0, 7, pack.revision)
	check(pack.reserve(1, 7, pack.revision) == TofuPackRules.Outcome.INVALID, "actor cannot carry multiple slabs")
	var replica := TofuPackRules.new()
	packet = JSON.parse_string(JSON.stringify(pack.capture(true)))
	check(replica.restore(packet, true) and replica.owners[0] == 7 and replica.revision == pack.revision, "live snapshot preserves slab reservation")
	check(replica.reserve(0, 8, replica.revision) == TofuPackRules.Outcome.INVALID, "replica sees occupied reservation")
	check(replica.restore(packet) and replica.owners[0] == 0, "reload releases slab reservation")
	invalid = pack.capture(true)
	invalid.owners[1] = 7
	check(not replica.restore(invalid, true), "duplicate carried slabs rejected")

func _test_accessible() -> void:
	var press := TofuPressRules.new()
	check(not press.accessible and press.release_tolerance() == 0.75, "standard timing remains default")
	check(press.gauge_minimum() == 82.0 and press.gauge_maximum() == 90.0, "standard gauge band remains exact")
	check(press.set_accessible(true, 1, press.revision) == TofuPressRules.Outcome.ACCEPTED, "explicit preset accepted")
	check(press.release_tolerance() == 1.25 and press.gauge_minimum() == 78.0 and press.gauge_maximum() == 94.0, "wider preset tuning")
	press.begin_traditional(TofuPressRules.Sample.SOFT, 1, 0.0, press.revision)
	press.place_stone("stone_1", 1, 0.0, press.revision)
	check(press.release_traditional(1, 1.75, press.revision) == TofuPressRules.Outcome.CERTIFIED, "accessible lower release boundary")
	press.begin_traditional(TofuPressRules.Sample.FIRM, 1, 10.0, press.revision)
	press.place_stone("stone_1", 1, 10.0, press.revision)
	press.place_stone("stone_2", 1, 10.0, press.revision)
	check(press.set_accessible(false, 2, press.revision) == TofuPressRules.Outcome.INVALID, "guest cannot change another actor trial preset")
	check(press.set_accessible(false, 1, press.revision) == TofuPressRules.Outcome.ACCEPTED, "preset change cancels trial")
	check(press.active_sample == -1 and press.lease_actor == 0 and not press.rejected and press.stones.is_empty(), "preset cancellation creates no mistake")
	check(press.certificates[0] and not press.certificates[1], "preset change keeps completed certificate only")
	check(press.release_traditional(1, 15.0, press.revision) == TofuPressRules.Outcome.INVALID, "canceled trial cannot certify")
	press.set_accessible(true, 1, press.revision)
	press.certificates[1] = true
	press.start_modern(1, 20.0, press.revision)
	var live := TofuPressRules.new()
	check(live.restore(JSON.parse_string(JSON.stringify(press.capture(true))), true) and live.accessible and live.active_sample == 2, "live snapshot retains preset and trial")
	var reloaded := TofuPressRules.new()
	check(reloaded.restore(press.capture()) and reloaded.accessible and reloaded.active_sample == -1, "reload keeps preset while canceling trial")
	check(press.stop_modern(1, 26.24, press.revision) == TofuPressRules.Outcome.CERTIFIED, "accessible lower gauge boundary")
	var upper := TofuPressRules.new()
	upper.certificates = [true, true, false]
	upper.set_accessible(true, 1, upper.revision)
	upper.start_modern(1, 0.0, upper.revision)
	check(upper.poll_modern(7.52) == TofuPressRules.Outcome.INVALID, "accessible upper band remains inclusive")
	check(upper.stop_modern(1, 7.52, upper.revision) == TofuPressRules.Outcome.CERTIFIED, "accessible upper gauge boundary")
	var legacy: Dictionary = upper.capture()
	legacy.erase("accessible")
	check(reloaded.restore(legacy) and not reloaded.accessible, "legacy snapshots default to standard preset")
	legacy["accessible"] = "true"
	check(not reloaded.restore(legacy), "malformed preset rejected")
